# Generated by Django 6.1 on 2026-09-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
